// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(BasicInfoContext))]
    partial class BasicInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinalProject.Models.BasicInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("collegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("BasicInfos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            birthDate = new DateTime(2003, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            collegeProgram = "IT",
                            name = "Andrew Grosko",
                            yearInProgram = "Junior"
                        },
                        new
                        {
                            id = 2,
                            birthDate = new DateTime(2002, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            collegeProgram = "Mechanical Engineering",
                            name = "Liam Brian",
                            yearInProgram = "Senior"
                        },
                        new
                        {
                            id = 3,
                            birthDate = new DateTime(2003, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            collegeProgram = "Media Production",
                            name = "Ireland Castle",
                            yearInProgram = "Junior"
                        },
                        new
                        {
                            id = 4,
                            birthDate = new DateTime(2002, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            collegeProgram = "Health Sciences",
                            name = "Elizabeth Stolle",
                            yearInProgram = "Senior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
