// <auto-generated />
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations.FavSong
{
    [DbContext(typeof(FavSongContext))]
    partial class FavSongContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinalProject.Models.FavSong", b =>
                {
                    b.Property<int>("iD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iD"), 1L, 1);

                    b.Property<string>("artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("song")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iD");

                    b.ToTable("FavSongs");

                    b.HasData(
                        new
                        {
                            iD = 1,
                            artist = "Zach Bryan",
                            genre = "Country",
                            name = "Andrew Grosko",
                            song = "Whiskey Fever"
                        },
                        new
                        {
                            iD = 2,
                            artist = "Morgan Wallen",
                            genre = "Country",
                            name = "Liam Brian",
                            song = "One Thing at a Time"
                        },
                        new
                        {
                            iD = 3,
                            artist = "Wham",
                            genre = "Christmas",
                            name = "Ireland Castle",
                            song = "Last Christmas"
                        },
                        new
                        {
                            iD = 4,
                            artist = "Morgan Wallen",
                            genre = "Country",
                            name = "Elizabeth Stolle",
                            song = "Last Night"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
